### ISSUE TITLE
ApiValueError invalid type, but file is successfully pinned

### ISSUE THREAD

**Issue by hududed** [nftstorage/python-client#1]
trying to simple storing function based on the example for store:
```
def create_ipfs(object):
    """Uploads object to IPFS using NFT storage"""
    configuration = nft_storage.Configuration(
        access_token = MY_TOKEN
    )

    with nft_storage.ApiClient(configuration) as api_client:
        api_instance = nft_storage_api.NFTStorageAPI(api_client)
        with open(object,'rb') as body:
            try:
                api_response = api_instance.store(body)
                pprint(api_response)
            except nft_storage.ApiException as e:
                print("Exception when calling NFTStorageAPI->store: %s\n" % e)
```
This gives me an error:
```
>>> create_ipfs('./test.jpeg')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/hud/nft-license/nft_utils.py", line 30, in create_ipfs
    api_response = api_instance.store(body)
  File "/usr/local/lib/python3.9/site-packages/nft_storage/api_client.py", line 771, in __call__
    return self.callable(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/nft_storage/api/nft_storage_api.py", line 471, in __store
    return self.call_with_http_info(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/nft_storage/api_client.py", line 833, in call_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.9/site-packages/nft_storage/api_client.py", line 408, in call_api
    return self.__call_api(resource_path, method,
  File "/usr/local/lib/python3.9/site-packages/nft_storage/api_client.py", line 223, in __call_api
    return_data = self.deserialize(
  File "/usr/local/lib/python3.9/site-packages/nft_storage/api_client.py", line 324, in deserialize
    deserialized_data = validate_and_convert_types(
  File "/usr/local/lib/python3.9/site-packages/nft_storage/model_utils.py", line 1394, in validate_and_convert_types
    converted_instance = attempt_convert_item(
  File "/usr/local/lib/python3.9/site-packages/nft_storage/model_utils.py", line 1290, in attempt_convert_item
    raise conversion_exc
  File "/usr/local/lib/python3.9/site-packages/nft_storage/model_utils.py", line 1281, in attempt_convert_item
    return deserialize_model(input_value, valid_class,
  File "/usr/local/lib/python3.9/site-packages/nft_storage/model_utils.py", line 1201, in deserialize_model
    return model_class(**kw_args)
  File "/usr/local/lib/python3.9/site-packages/nft_storage/model_utils.py", line 1566, in wrapped_init
    return fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/nft_storage/model/upload_response.py", line 174, in __init__
    setattr(self, var_name, var_value)
  File "/usr/local/lib/python3.9/site-packages/nft_storage/model_utils.py", line 167, in __setattr__
    self[attr] = value
  File "/usr/local/lib/python3.9/site-packages/nft_storage/model_utils.py", line 352, in __setitem__
    self.set_attribute(name, value)
  File "/usr/local/lib/python3.9/site-packages/nft_storage/model_utils.py", line 139, in set_attribute
    value = validate_and_convert_types(
  File "/usr/local/lib/python3.9/site-packages/nft_storage/model_utils.py", line 1394, in validate_and_convert_types
    converted_instance = attempt_convert_item(
  File "/usr/local/lib/python3.9/site-packages/nft_storage/model_utils.py", line 1290, in attempt_convert_item
    raise conversion_exc
  File "/usr/local/lib/python3.9/site-packages/nft_storage/model_utils.py", line 1281, in attempt_convert_item
    return deserialize_model(input_value, valid_class,
  File "/usr/local/lib/python3.9/site-packages/nft_storage/model_utils.py", line 1201, in deserialize_model
    return model_class(**kw_args)
  File "/usr/local/lib/python3.9/site-packages/nft_storage/model_utils.py", line 1566, in wrapped_init
    return fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/nft_storage/model/nft.py", line 202, in __init__
    setattr(self, var_name, var_value)
  File "/usr/local/lib/python3.9/site-packages/nft_storage/model_utils.py", line 167, in __setattr__
    self[attr] = value
  File "/usr/local/lib/python3.9/site-packages/nft_storage/model_utils.py", line 352, in __setitem__
    self.set_attribute(name, value)
  File "/usr/local/lib/python3.9/site-packages/nft_storage/model_utils.py", line 143, in set_attribute
    check_allowed_values(
  File "/usr/local/lib/python3.9/site-packages/nft_storage/model_utils.py", line 700, in check_allowed_values
    raise ApiValueError(
nft_storage.exceptions.ApiValueError: Invalid value for `type` (image/png), must be one of ['directory', 'image/jpeg', 'application/json', 'other mime types']
```

The image is not a png, and the image is also successfully uploaded under nft.storage/files site. Please advise

**Comment by dchoi27** [comment]
Will fix along with issue here: https://github.com/ipfs-shipyard/nft.storage/issues/291

**Comment by Gozala** [comment]
I'm not sure I understand how this client is generated, @olizilla I think you said  scripts are in the repo to do so, but I'm not seeing them, mind pointing me ?

**Comment by olizilla** [comment]
https://github.com/ipfs-shipyard/nft.storage/blob/main/client-gen.sh

**Comment by korabs-x** [comment]
This avoids the error and returns the cid:
`api_response = api_instance.store(body, _check_return_type=False)`
