### ISSUE TITLE
Issue uploading .car file 

### ISSUE THREAD

**Issue by vguerrera-via** [nftstorage/python-client#5]
I seem to be receiving an invalid type error when uploading a .car file using the store method

Here is the code snippet I am using : 

```
configuration = nft_storage.Configuration(
        access_token=api_key
    )

with nft_storage.ApiClient(configuration=configuration, header_name='Content-type', header_value='application/car') as api_client:
        api_instance = nft_storage_api.NFTStorageAPI(api_client)
        with open("example.car", 'rb') as body:
            
         try:
            # Store a file
            api_response = api_instance.store(body)
            print(api_response)

            return api_response["value"]["cid"]
          except nft_storage.ApiException as e:
            print("Exception when calling NFTStorageAPI->store: %s\n" % e)
```

And this is the error I am receiving : 

```
Traceback (most recent call last):
File "/home/pysetup/.venv/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 404, in run_asgi
  result = await app(  # type: ignore[func-returns-value]
File "/home/pysetup/.venv/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
  return await self.app(scope, receive, send)
File "/home/pysetup/.venv/lib/python3.9/site-packages/fastapi/applications.py", line 269, in __call__
  await super().__call__(scope, receive, send)
File "/home/pysetup/.venv/lib/python3.9/site-packages/starlette/applications.py", line 124, in __call__
  await self.middleware_stack(scope, receive, send)
File "/home/pysetup/.venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
  raise exc
File "/home/pysetup/.venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
  await self.app(scope, receive, _send)
File "/home/pysetup/.venv/lib/python3.9/site-packages/starlette/middleware/cors.py", line 84, in __call__
  await self.app(scope, receive, send)
File "/home/pysetup/.venv/lib/python3.9/site-packages/starlette/exceptions.py", line 93, in __call__
  raise exc
File "/home/pysetup/.venv/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
  await self.app(scope, receive, sender)
File "/home/pysetup/.venv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
  raise e
File "/home/pysetup/.venv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
  await self.app(scope, receive, send)
File "/home/pysetup/.venv/lib/python3.9/site-packages/starlette/routing.py", line 670, in __call__
  await route.handle(scope, receive, send)
File "/home/pysetup/.venv/lib/python3.9/site-packages/starlette/routing.py", line 266, in handle
  await self.app(scope, receive, send)
File "/home/pysetup/.venv/lib/python3.9/site-packages/starlette/routing.py", line 65, in app
  response = await func(request)
File "/home/pysetup/.venv/lib/python3.9/site-packages/fastapi/routing.py", line 227, in app
  raw_response = await run_endpoint_function(
File "/home/pysetup/.venv/lib/python3.9/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
  return await run_in_threadpool(dependant.call, **values)
File "/home/pysetup/.venv/lib/python3.9/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
  return await anyio.to_thread.run_sync(func, *args)
File "/home/pysetup/.venv/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
  return await get_asynclib().run_sync_in_worker_thread(
File "/home/pysetup/.venv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
  return await future
File "/home/pysetup/.venv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
  result = context.run(func, *args)
File "/app/routers/answers.py", line 38, in get_proof
  cid = upload_to_IPFS("test")
File "/app/proof.py", line 65, in upload_to_IPFS
  api_response = api_instance.store(body)
File "/home/pysetup/.venv/lib/python3.9/site-packages/nft_storage/api_client.py", line 771, in __call__
  return self.callable(self, *args, **kwargs)
File "/home/pysetup/.venv/lib/python3.9/site-packages/nft_storage/api/nft_storage_api.py", line 589, in __store
  return self.call_with_http_info(**kwargs)
File "/home/pysetup/.venv/lib/python3.9/site-packages/nft_storage/api_client.py", line 833, in call_with_http_info
  return self.api_client.call_api(
File "/home/pysetup/.venv/lib/python3.9/site-packages/nft_storage/api_client.py", line 408, in call_api
  return self.__call_api(resource_path, method,
File "/home/pysetup/.venv/lib/python3.9/site-packages/nft_storage/api_client.py", line 223, in __call_api
  return_data = self.deserialize(
File "/home/pysetup/.venv/lib/python3.9/site-packages/nft_storage/api_client.py", line 324, in deserialize
  deserialized_data = validate_and_convert_types(
File "/home/pysetup/.venv/lib/python3.9/site-packages/nft_storage/model_utils.py", line 1543, in validate_and_convert_types
  converted_instance = attempt_convert_item(
File "/home/pysetup/.venv/lib/python3.9/site-packages/nft_storage/model_utils.py", line 1436, in attempt_convert_item
  raise conversion_exc
File "/home/pysetup/.venv/lib/python3.9/site-packages/nft_storage/model_utils.py", line 1427, in attempt_convert_item
  return deserialize_model(input_value, valid_class,
File "/home/pysetup/.venv/lib/python3.9/site-packages/nft_storage/model_utils.py", line 1347, in deserialize_model
  return model_class._new_from_openapi_data(**kw_args)
File "/home/pysetup/.venv/lib/python3.9/site-packages/nft_storage/model_utils.py", line 44, in wrapped_init
  return fn(_self, *args, **kwargs)
File "/home/pysetup/.venv/lib/python3.9/site-packages/nft_storage/model_utils.py", line 343, in _new_from_openapi_data
  return cls._from_openapi_data(*args, **kwargs)
File "/home/pysetup/.venv/lib/python3.9/site-packages/nft_storage/model_utils.py", line 44, in wrapped_init
  return fn(_self, *args, **kwargs)
File "/home/pysetup/.venv/lib/python3.9/site-packages/nft_storage/model/upload_response.py", line 181, in _from_openapi_data
  setattr(self, var_name, var_value)
File "/home/pysetup/.venv/lib/python3.9/site-packages/nft_storage/model_utils.py", line 183, in __setattr__
  self[attr] = value
File "/home/pysetup/.venv/lib/python3.9/site-packages/nft_storage/model_utils.py", line 483, in __setitem__
  self.set_attribute(name, value)
File "/home/pysetup/.venv/lib/python3.9/site-packages/nft_storage/model_utils.py", line 155, in set_attribute
  value = validate_and_convert_types(
File "/home/pysetup/.venv/lib/python3.9/site-packages/nft_storage/model_utils.py", line 1543, in validate_and_convert_types
  converted_instance = attempt_convert_item(
File "/home/pysetup/.venv/lib/python3.9/site-packages/nft_storage/model_utils.py", line 1436, in attempt_convert_item
  raise conversion_exc
File "/home/pysetup/.venv/lib/python3.9/site-packages/nft_storage/model_utils.py", line 1427, in attempt_convert_item
  return deserialize_model(input_value, valid_class,
File "/home/pysetup/.venv/lib/python3.9/site-packages/nft_storage/model_utils.py", line 1347, in deserialize_model
  return model_class._new_from_openapi_data(**kw_args)
File "/home/pysetup/.venv/lib/python3.9/site-packages/nft_storage/model_utils.py", line 44, in wrapped_init
  return fn(_self, *args, **kwargs)
File "/home/pysetup/.venv/lib/python3.9/site-packages/nft_storage/model_utils.py", line 343, in _new_from_openapi_data
  return cls._from_openapi_data(*args, **kwargs)
File "/home/pysetup/.venv/lib/python3.9/site-packages/nft_storage/model_utils.py", line 44, in wrapped_init
  return fn(_self, *args, **kwargs)
File "/home/pysetup/.venv/lib/python3.9/site-packages/nft_storage/model/nft.py", line 209, in _from_openapi_data
  setattr(self, var_name, var_value)
File "/home/pysetup/.venv/lib/python3.9/site-packages/nft_storage/model_utils.py", line 183, in __setattr__
  self[attr] = value
File "/home/pysetup/.venv/lib/python3.9/site-packages/nft_storage/model_utils.py", line 483, in __setitem__
  self.set_attribute(name, value)
File "/home/pysetup/.venv/lib/python3.9/site-packages/nft_storage/model_utils.py", line 159, in set_attribute
  check_allowed_values(
File "/home/pysetup/.venv/lib/python3.9/site-packages/nft_storage/model_utils.py", line 846, in check_allowed_values
  raise ApiValueError(
nft_storage.exceptions.ApiValueError: Invalid value for `type` (image/*, application/car), must be one of ['directory', 'image/jpeg', 'application/json', 'other mime types']

```

**Comment by vguerrera-via** [comment]
Closing issue, as it seems by adding `_check_return_type=False` to `api_instance.store(body, _check_return_type=False)`. No error is thrown and the CID is returned
